### ISSUE TITLE
ScanID is not editable from the GUI and will not recover after Sardana restart

### ISSUE THREAD

**Issue by lrlunin** [nexdatas/selector#78]
After we have our sardana restarted the configuration in the nxselector was lost (it is fine) but then we could not edit the ScanID anymore. I am aware, there is an option to set it in Sardana internally with spock `%setenv ScanID XXX`.

However, I afraid that unexperienced user which could begin the measurement without setting the ScanID. We use a `sample_name_%05` filename which includes the ScanID as a parameter to write the scans into separate files. Then, I assume, if ScanID was empty it would be set automatically to 0. Then the next scan could overwrite the already existing file.

I did not tried this out but could you please check this. Otherwise, it can be really dangerous for the people who has no experience with Sardana control system.

**Comment by jkotan** [comment]
Hello @lrlunin,
Actually,  scanID is read-only for security reasons, i.e. to disallow users accidentally change scanID which is set automatically by a scan macro. But I can add a swtich in the nxselector configuration to make it editable.
